### ISSUE TITLE
Could not find any configuration file!

### ISSUE THREAD

**Issue by jmeeter** [ZerataX/matrix-registration#24]
**Describe the bug**

While installing matrix-registration, I receive the following output:

> root@xxx:~# python3 -m matrix_registration
> could not find any configuration file!

Try to define config file, receive

> root@xxxx:/# python3 -m matrix_registration --config-path /usr/local/config/config.yaml
> could not find any configuration file!

**System:**
 - OS: Ubuntu 18.04
 - python version: 3.6
 - matrix registration version: latest

**Comment by Bubu** [comment]
Are you using latest release or master?

**Comment by ZerataX** [comment]
it's now finally the latest release as well and since nobody responded to this i will assume it's not an issue any longer

**Comment by vpzomtrrfrt** [comment]
I'm seeing this issue with the v1.0.0.dev7 docker image

or at least a similar one, might only be broken in docker for all I know

**Comment by xelantro** [comment]
@vpzomtrrfrt (pls dont necro old issues) but have you tried this image https://hub.docker.com/repository/docker/jlj7/matrix-registration see https://github.com/zeratax/matrix-registration/issues/88
