### ISSUE TITLE
Date format depends on system locale?

### ISSUE THREAD

**Issue by kylrth** [ZerataX/matrix-registration#28]
I tried several times to create a new token with an expiry date, but the token wouldn't work. I was running the module (`python -m matrix_registration gen -e 01.04.2020`). When I tried using the `/token` API, I realized that I was actually getting a token with expiry on Jan 04, 2020! It sounds like the date formatter might depend on my system locale or something like that. Can we fix it so the format is always `DD.MM.YYYY`?

**Comment by ZerataX** [comment]
Probably should just change it to ISO 8601 so `YYYY.MM.DD` since that should be unambiguous everywhere

**Comment by kylrth** [comment]
Yes, that would be best.

**Comment by ZerataX** [comment]
fixed in 588025dac2d8aa8d40a11fd4dd9aac7773a66840 with will be in the shortly coming **v0.6.0**
