### ISSUE TITLE
Instructions on how to deploy as wsgi server

### ISSUE THREAD

**Issue by seanhagen** [ZerataX/matrix-registration#32]
I've got matrix-registration running but I'd like to know how to have it set up as a service so I don't have to worry about manually starting/restarting it on the server I've got running. 

Basically I want to get rid of these lines:
```
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
```
Which show up when I run `python3 -m matrix_registration api`

**Comment by ZerataX** [comment]
I think since v0.5.6 it should always just run as a wsgi server
