### ISSUE TITLE
Bundle font instead of using google fonts

### ISSUE THREAD

**Issue by Bubu** [ZerataX/matrix-registration#36]
This should be a win for both privacy and load times.

Unfortunately it's not trivial to replace and not zero cost. I found some in-depth discussion about this here: https://www.tunetheweb.com/blog/should-you-self-host-google-fonts/

**Comment by ZerataX** [comment]
sounds good yeah, just wonder if there's anything regarding licenses I have to consider

**Comment by passw0rd123** [comment]
As I understand this, it stands under a free license even for commercial use:
https://fonts.google.com/specimen/Nunito#license

> **License**
> These fonts are licensed under the Open Font License. (https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL)
> 
> You can use them freely in your products & projects - print or digital, commercial or otherwise. However, you can't sell the fonts on their own.
> 
> This isn't legal advice, please consider consulting a lawyer and see the full license for all details

So it would be great to get rid of this 3rd party ressources.
