### ISSUE TITLE
Invalid Tokens when Generated by Another Instance

### ISSUE THREAD

**Issue by Sneagan** [ZerataX/matrix-registration#37]
**Describe the bug**
Tokens added to the database by other means are not detected by `matrix-registration`.

**To Reproduce**

1. Add a properly-formatted record to the `tokens` table without using `matrix-registration`
2. Attempt to create a user with this token
3. Token is invalid

**Expected behavior**
Any properly formatted token in the database should be valid.

**System:**
 - OS: ubuntu 18.04
 - python version: 3.6.9
 - matrix registration version: Unclear. Neither `pip show` nor `python3 -m matrix_registration -h` show version.

**Additional context**
I am running one instance of `matrix_registration` on a host and another in a container. The two share a database and I can confirm that writes from both instances of the application are persisting in the same table. However, the instances will only validate records they created themselves and report records created by the other instance as invalid. This is confusing to me because the [load function](https://github.com/ZerataX/matrix-registration/blob/b6fdaab6071a72c8ab32d2bc8816a94c2e32ddaa/matrix_registration/tokens.py#L94) looks like it should refresh all tokens from the database and it looks like it is being called during validation. This makes me wonder if there is additional state being saved somewhere that is causing these instances to ignore one another's records.

**Comment by Sneagan** [comment]
As is so often the case, I discovered the issue after posting here thinking I had considered everything. The issue was that one of the instances was setting expiration day and month backwards, causing all of the tokens not generated on the same day as the month number (i.e. 08-08) to be invalid. Apologies for the false bug and thanks for the great project.

**Comment by ZerataX** [comment]
hmm yeah we've recently switched to ISO 8601, which should be unambiguous, but I guess it still accepts dates without year which makes ambiguous again?

In any case this is a useful report as it reminded me that I need a easy way to check project version and look into if the current version allows anything other than ISO-8601.
