### ISSUE TITLE
Unrecognized request

### ISSUE THREAD

**Issue by boogewooge** [ZerataX/matrix-registration#40]
**Describe the bug**

After updating synapse to 1.24, registrations now fail for me with "Unrecognized request". Worked fine before.

**To Reproduce**

1. Have synapse 1.24 on the homeserver
2. Have matrix-registration installed and the daemon running
3. Try to register with the web interface or
```
curl -X POST \
     -F 'username=test' \
     -F 'password=verysecure' \
     -F 'confirm=verysecure' \
     -F 'token=DoubleWizardSki' \
     http://localhost:5000/register
```
4. Be me?

**Expected behavior**

Successful registration.

**Actual behavior**
`{"errcode":"M_UNRECOGNIZED","error":"Unrecognized request"}`

**System:**
 - OS: Ubuntu
 - python version: 3.8
 - matrix registration version: 0.7.0

**Comment by ZerataX** [comment]
I assume this is related to #39 so probably soon fixed

**Comment by throwawayay** [comment]
Bump on this, would be great if you could merge #41 (I believe tests should pass afterwards) and tag a new release, so upstreams like https://github.com/spantaleev/matrix-docker-ansible-deploy can also be fixed.

Thanks!
