### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by spantaleev** [ZerataX/matrix-registration#43]
v0.7.0 doesn't work with Synapse v1.24.0, because the registration API has been moved from `/_matrix/client/r0/admin/register` to `/_synapse/admin/v1/register`.

This has already been fixed in 6b26255feada4c, but since there hasn't been a new release since then, most of us were on v0.7.0 and matrix-registration was failing.

**Comment by ZerataX** [comment]
Yeah I'm sorry for the delay,

There were some other issues, since flask-SQLalchemy also introduced bugs into the build environment that I couldn't immediately reproduce locally

https://github.com/ZerataX/matrix-registration/releases/tag/v0.7.1

**Comment by spantaleev** [comment]
Awesome! Thanks for the quick fix!
