### ISSUE TITLE
base_url does not apply to the background image (specified in the CSS)

### ISSUE THREAD

**Issue by spantaleev** [ZerataX/matrix-registration#47]
Using a `base_url: /matrix-registration` configuration setting (implemented in 8dbabbcb6ec17) fixes URL generation and all assets are linked to in a way that preserves the base URL.

However, `styles.css` stylesheet hardcodes `/static/images/valley.jpg` in a way that doesn't respect the base URL:

https://github.com/ZerataX/matrix-registration/blob/8698bd51d9908e8349a9221830dd76a7b4cc5436/matrix_registration/static/css/style.css#L9

Thus, people still need to rewrite `/static` to something like `/matrix-registration/static` for `text/css` resources.

Having `base_url` support is a huge improvement, but putting `matrix-registration` under a different path still requires some manual work like this.

**Comment by ZerataX** [comment]
v0.8.0.dev1 should fix this, but I haven't yet published a release until I tested this more.
I also created a translation system (https://l10n.dmnd.sh/engage/matrix-registration/) which I probably shouldn't have pushed at the same time, but ...

**Comment by spantaleev** [comment]
I've commented on 6e7561fb47a2, but not sure if you got a notification about it.

Wouldn't this still be problematic (it's not using `base_url`) in any way?

https://github.com/ZerataX/matrix-registration/blob/ba6f6bcd8d966aff87479b215f102c7ac99080bb/matrix_registration/templates/register.html#L22

**Comment by ZerataX** [comment]
ehm yes sorry that is problematic
