### ISSUE TITLE
choose path to log and sqlite files

### ISSUE THREAD

**Issue by FacesHC** [ZerataX/matrix-registration#53]
**Is your feature request related to a problem?**

It's very annoying to have a new Sqlite3file created where you input the startup command ! You can loose your previous tokens and it create garbage files each time you start the command.

**Describe the solution you'd like**

Add to the config.yaml  where you want to store the log and sqlite file. Like path_to_logs = ""; 
It would be easier for new users 

Regards

**Comment by ZerataX** [comment]
those both already are options?
https://github.com/ZerataX/matrix-registration/blob/8dbabbcb6ec177e7ef91c6ff5e3b1d650370200e/config.sample.yaml#L7
https://github.com/ZerataX/matrix-registration/blob/8dbabbcb6ec177e7ef91c6ff5e3b1d650370200e/config.sample.yaml#L33
