### ISSUE TITLE
Documentation for Curl suggests use of SharedSecret where AdminAPIPass is actually required

### ISSUE THREAD

**Issue by squarepupil** [ZerataX/matrix-registration#58]
**Describe the bug**

The api documentation in the [api documentation](https://github.com/ZerataX/matrix-registration/wiki/api) suggests that one should use the `SharedSecret`:

```
curl -X POST \
     -H "Authorization: SharedSecret verysecuresecret" \
     -H "Content-Type: application/json" \
     -d '{"one_time": true, "ex_date": "24.12.2020"}' \
     http://localhost:5000/token
```
@ZerataX clarified for me in #matrix-registration:dmnd.sh that the `AdminAPIPass` belongs in that field. This was confusing as I was coming from a previous version of matrix-registration in which `SharedSecret` _was_ the necessary credential in this field.

The [Readme](https://github.com/ZerataX/matrix-registration/blob/master/README.md) also does not clarify which `password` is meant in the curl example given.
```
curl -X POST \
     -F 'username=test' \
     -F 'password=verysecure' \
     -F 'confirm=verysecure' \
     -F 'token=DoubleWizardSki' \
     http://localhost:5000/register
```

**To Reproduce**

1. Attempt any of the above curl commands using the now-unsupported `SharedSecret` (i.e., the Synapse shared secret found in homeserver.yaml)
2. Note failure

**Expected behavior**

Documentation should expressly specify `AdminAPIPass` in commands where it is required.

**Comment by olmari** [comment]
well... "shared secret" IS what the admin api token is... an secret that is shared between the automaton and admin user...  So it is not wrong either...

**Comment by squarepupil** [comment]
I should also mention that the error code if you enter the wrong credential is also misleading: `{"errcode":"MR_BAD_SECRET","error":"wrong shared secret"}`

This again suggests that it is `SharedSecret` that we're looking for and _not_ `AdminAPIPass`

**Comment by squarepupil** [comment]
> 
> 
> well... "shared secret" IS what the admin api token is... an secret that is shared between the automaton and admin user... So it is not wrong either...

![image](https://user-images.githubusercontent.com/5905665/105240258-0630ed80-5b3b-11eb-9325-7a0c9e191581.png)

You're suggesting that when I'm asked for "shared secret" I should be inputting "admin secret" instead of "shared secret", the one with the same exact name?

**Comment by lantrix** [comment]
As far as I can tell `shared_secret` here shows a value of `RegistrationSharedSecret` which seems to me would be:

- For Synapse homeserver the [`registration_shared_secret`](https://github.com/matrix-org/synapse/blob/develop/docker/conf/homeserver.yaml#L151)
- For Dendrite homeserver the [`registration_shared_secret`](https://github.com/matrix-org/dendrite/blob/master/dendrite-config.yaml#L145)

I'm trying to set this up too.

**Comment by ZerataX** [comment]
ehm sorry for not being active in so long, real life stuff happened. anywas
@lantrix yeah you're correct it does correspond to these value. idk if it works with dendrite though, i am using a specific synapse api that is not part of the matrix spec.

@squarepupil Before I left I was working on a 1.0.0 release and wanted to rename a lot of variables to make more sense, so I am totally open to renaming these config values. 
would `registration_shared_secret `and `admin_api_secret `make more sense?
