### ISSUE TITLE
config.sample.yaml server_location: localhost or https?

### ISSUE THREAD

**Issue by seth586** [ZerataX/matrix-registration#61]
The documented [config.sample.yaml](https://github.com/ZerataX/matrix-registration/blob/master/config.sample.yaml) indicates `server_location: 'https://matrix.org'` as an example url for server location, but this requires nginx to forward `https://example.tld/_synapse/admin/v1/register` to the whole world. 

According to the official [synapse reverse proxy documentation](https://github.com/matrix-org/synapse/blob/develop/docs/reverse_proxy.md#nginx), only location `/_synapse/client` should be forwarded.

For my configuration of matrix-registration I used `server_location: 'http://localhost:8008'`, which I believe to be more secure.

Should config.sample.yaml show this, or am I missing something?

**Comment by ZerataX** [comment]
yeah if you have both on the same machine that is definitely ideal. Not completely sure how to indicate that in the config sample.

**Comment by seth586** [comment]
Ok just making sure I didn't miss something, thanks!
