### ISSUE TITLE
Add /api to nginx reverse proxy while using williamkray / maubot-invite

### ISSUE THREAD

**Issue by a000a** [ZerataX/matrix-registration#66]
if using the latest version of matrix-registration with https://github.com/williamkray/maubot-invite and nginx reverse proxy, additionally this should be added to nginx.conf inside the corresponding server to show generation link correctly.

```
    location /api {
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_pass http://localhost:5000;
    }
```

**Comment by ZerataX** [comment]
yeah it's mentioned in the wiki
https://github.com/ZerataX/matrix-registration/wiki/reverse-proxy#optional

maybe it should be mentioned somewhere else, not sure what your suggestion is?

**Comment by ZerataX** [comment]
closing this due to lack of response, feel free to reopen

**Comment by a000a** [comment]
Sorry,  fell out of my perspective..
wasn't aware of the wiki. and even read over the link on the readme page. my fault.
