### ISSUE TITLE
Using the Registration with Postgres cannot start as the SQL database initialization fails

### ISSUE THREAD

**Issue by donicrosby** [ZerataX/matrix-registration#67]
**Describe the bug**

Serving the registration app with a postgres backed database fails as multiple steps in the database creation process are not done
- The ips table does not have a unique constraint with address
- Manually adding the constraint still fails as the token and name are incompatible types

**To Reproduce**

1. Create a new postgres database with "createdb -O \<registration-user\> \<registration-table\>"
2. Connect to the postgres database using the "postgress://..." connection string
3. The container will crash hard and will not start up and will display the error about unique constraints, fixing that it still will not start as there are incompatible types with the token and name

**Expected behavior**

Database is successfully created and the container will start

**Screenshots**

N/A

**System:**
 - OS: Ubuntu (Docker/K8s)
 - python version: Docker container version
 - matrix registration version: v0.9.1/v0,9.1.post1

**Additional context**

N/A

**Comment by ZerataX** [comment]
`pip install matrix-registration==1.0.0.dev5`
this release should fix it

**Comment by ZerataX** [comment]
alright docker image:
`docker pull zeratax/matrix-registration:v1.0.0.dev6`

**Comment by donicrosby** [comment]
That seemed to work, thanks for the quick update!
