### ISSUE TITLE
Add Support for deleting tokens from the database via API

### ISSUE THREAD

**Issue by thefeiter** [zeratax/matrix-registration#81]
**Is your feature request related to a problem?**

Not really, I just would like to be able to clean up the database via the API.

**Describe the solution you'd like**

A possible API call for deleting a specified token.

**Comment by xelantro** [comment]
I implemented the delete protokoll for the token endpoint
```bash
curl -X DELETE \
     -H "Authorization: SharedSecret <APIAdminPassword>" \
     -H "Content-Type: application/json" \
     http://localhost:5000/api/token/<token_name>

-> {"success": true}
```
although - I might still change the response
