### ISSUE TITLE
Not compatible with flask-limiter >= 2.0.1, but `setup.py` will cause it to be installed anyways

### ISSUE THREAD

**Issue by jeffcasavant** [ZerataX/matrix-registration#84]
I installed matrix-registration on my system a long time ago.  Recently when reinstalling into a new system, I got the following error when trying to run `matrix-registration serve`:

```
Traceback (most recent call last):
  File "/root/.local/bin/matrix-registration", line 5, in <module>
    from matrix_registration.app import cli
  File "/root/.local/pipx/venvs/matrix-registration/lib/python3.7/site-packages/matrix_registration/app.py", line 9, in <module>
    from flask_limiter.util import get_ipaddr
ImportError: cannot import name 'get_ipaddr' from 'flask_limiter.util' (/root/.local/pipx/venvs/matrix-registration/lib/python3.7/site-packages/flask_limiter/util.py)
```

I downgraded `flask-limiter` to 2.0.0 and the application then runs fine.

You should be able to replicate this by installing `matrix-registration` using `pip` (or `pipx` as in my case) without any constraints as recommended in the README and running `matrix-registration serve`.  Then you should be able to get it running again using `pip install flask-limiter==2.0.0` (or `pipx runpip matrix-registration install flask-limiter==2.0.0`, as in my case).

**Comment by xelantro** [comment]
#83 fixes this, be patient pls :D

**Comment by jeffcasavant** [comment]
Hey, awesome!  I searched for related issues but could not find any so I figured I'd go ahead & file this.  I left the `is:issue` flag in my search though :stuck_out_tongue: .  Thanks @xelantro !

**Comment by xelantro** [comment]
This should have fixed it, feel free to comment / reopen if you still have issiues.
Be aware that this is prob not live in pip yet (@ZerataX handels package stuff)

**Comment by jeffcasavant** [comment]
Thanks much!  I'll give it a shot.
