### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by paboum** [zeratax/matrix-registration#98]
### Description of the new feature / enhancement

No commits for the past year, three bugs occuring in most simple use cases just after installation, no meaningful response from the dev team in 24h after a bug report.

### Scenario when this would be used?

Might be simply better to shutdown the project, provide links to more robust and hopeful alternatives.

**Comment by Bubu** [comment]
I'm using this project from the master branch (via https://aur.archlinux.org/packages/matrix-registration-git, which I maintain) without any problems. (except the usual python dependency churn, which can be worked around downstream. I.e. I just integrated https://github.com/zeratax/matrix-registration/pull/99)

> no meaningful response from the dev team in 24h after a bug report.

A 24 hour response expectation for a single-person entirely volunteer side-project is totally unreasonable in my opinion. People are usually busy with many other things (maybe even other foss projects) in their live. Sometimes it takes a few months for the maintainer to get back to a particular project. Or they never do at all and others carry it forward.

And yes, a maintenance release would be appreciated at some point... but the project is still useful in the state it is. :-)

**Comment by zeratax** [comment]
spent some time recently reworking the docker stuff. should i think now be possible to support multiple architectures ^^
also just tried to rework some of the heavily nested code lol. want to test it a bit more before pushing it
